// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mocker.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	mocker.proto

It has these top-level messages:
	HandleRequest
	HandleResponse
	Request
	HeaderValue
	Response
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type HandleRequest struct {
	Request  *Request  `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Response *Response `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
}

func (m *HandleRequest) Reset()                    { *m = HandleRequest{} }
func (m *HandleRequest) String() string            { return proto1.CompactTextString(m) }
func (*HandleRequest) ProtoMessage()               {}
func (*HandleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HandleRequest) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *HandleRequest) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type HandleResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *HandleResponse) Reset()                    { *m = HandleResponse{} }
func (m *HandleResponse) String() string            { return proto1.CompactTextString(m) }
func (*HandleResponse) ProtoMessage()               {}
func (*HandleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HandleResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Request struct {
	Method  string                  `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Path    string                  `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Query   map[string]string       `protobuf:"bytes,3,rep,name=query" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Headers map[string]*HeaderValue `protobuf:"bytes,4,rep,name=headers" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto1.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Request) GetQuery() map[string]string {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *Request) GetHeaders() map[string]*HeaderValue {
	if m != nil {
		return m.Headers
	}
	return nil
}

type HeaderValue struct {
	Value []string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *HeaderValue) Reset()                    { *m = HeaderValue{} }
func (m *HeaderValue) String() string            { return proto1.CompactTextString(m) }
func (*HeaderValue) ProtoMessage()               {}
func (*HeaderValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HeaderValue) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type Response struct {
	Status int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Body   string `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto1.RegisterType((*HandleRequest)(nil), "proto.HandleRequest")
	proto1.RegisterType((*HandleResponse)(nil), "proto.HandleResponse")
	proto1.RegisterType((*Request)(nil), "proto.Request")
	proto1.RegisterType((*HeaderValue)(nil), "proto.HeaderValue")
	proto1.RegisterType((*Response)(nil), "proto.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Mocker service

type MockerClient interface {
	Handle(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error)
}

type mockerClient struct {
	cc *grpc.ClientConn
}

func NewMockerClient(cc *grpc.ClientConn) MockerClient {
	return &mockerClient{cc}
}

func (c *mockerClient) Handle(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error) {
	out := new(HandleResponse)
	err := grpc.Invoke(ctx, "/proto.Mocker/Handle", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Mocker service

type MockerServer interface {
	Handle(context.Context, *HandleRequest) (*HandleResponse, error)
}

func RegisterMockerServer(s *grpc.Server, srv MockerServer) {
	s.RegisterService(&_Mocker_serviceDesc, srv)
}

func _Mocker_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockerServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Mocker/Handle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockerServer).Handle(ctx, req.(*HandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mocker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Mocker",
	HandlerType: (*MockerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _Mocker_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mocker.proto",
}

func init() { proto1.RegisterFile("mocker.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0xfd, 0xa5, 0x69, 0xd2, 0x76, 0xd2, 0x5f, 0x95, 0xa1, 0x96, 0x58, 0x2f, 0x25, 0x82, 0x04,
	0x84, 0x0a, 0x11, 0xb5, 0x78, 0xf3, 0x20, 0xf4, 0xa2, 0xe0, 0x1e, 0xbc, 0xa7, 0x66, 0xa4, 0xd0,
	0x3f, 0xdb, 0x6e, 0x36, 0x42, 0x3e, 0x91, 0x5f, 0x53, 0xb2, 0x7f, 0xd2, 0x58, 0x3c, 0x65, 0x66,
	0xde, 0x7b, 0xfb, 0x5e, 0x66, 0x17, 0xfa, 0x1b, 0xfe, 0xb1, 0x22, 0x31, 0xdd, 0x09, 0x2e, 0x39,
	0x7a, 0xea, 0x13, 0x7d, 0xc2, 0xff, 0x79, 0xba, 0xcd, 0xd6, 0xc4, 0x68, 0x5f, 0x50, 0x2e, 0x31,
	0x86, 0x8e, 0xd0, 0x65, 0xe8, 0x4c, 0x9c, 0x38, 0x48, 0x06, 0x5a, 0x30, 0x35, 0x04, 0x66, 0x61,
	0xbc, 0x86, 0xae, 0xa0, 0x7c, 0xc7, 0xb7, 0x39, 0x85, 0x2d, 0x45, 0x3d, 0xa9, 0xa9, 0x7a, 0xcc,
	0x6a, 0x42, 0x74, 0x05, 0x03, 0xeb, 0xa3, 0x27, 0x38, 0x04, 0x8f, 0x84, 0xe0, 0x42, 0xd9, 0xf4,
	0x98, 0x6e, 0xa2, 0xef, 0x16, 0x74, 0x6c, 0x94, 0x11, 0xf8, 0x1b, 0x92, 0x4b, 0x9e, 0x19, 0x8a,
	0xe9, 0x10, 0xa1, 0xbd, 0x4b, 0xe5, 0x52, 0x99, 0xf6, 0x98, 0xaa, 0xf1, 0x06, 0xbc, 0x7d, 0x41,
	0xa2, 0x0c, 0xdd, 0x89, 0x1b, 0x07, 0xc9, 0xf9, 0xef, 0xd0, 0xd3, 0xb7, 0x0a, 0x7b, 0xde, 0x4a,
	0x51, 0x32, 0xcd, 0xc3, 0x3b, 0xe8, 0x2c, 0x29, 0xcd, 0x48, 0xe4, 0x61, 0x5b, 0x49, 0x2e, 0x8e,
	0x24, 0x73, 0x8d, 0x6a, 0x91, 0xe5, 0x8e, 0x67, 0x00, 0x87, 0xb3, 0xf0, 0x14, 0xdc, 0x15, 0x95,
	0x26, 0x5e, 0x55, 0x56, 0x7f, 0xf5, 0x95, 0xae, 0x0b, 0x32, 0xe1, 0x74, 0xf3, 0xd8, 0x9a, 0x39,
	0xe3, 0x57, 0xe8, 0x37, 0x8f, 0xfc, 0x43, 0x1b, 0x37, 0xb5, 0x41, 0x82, 0x26, 0x90, 0x56, 0xbd,
	0x57, 0x48, 0xe3, 0xbc, 0xe8, 0x12, 0x82, 0x06, 0x72, 0x30, 0x76, 0x26, 0x6e, 0x6d, 0x1c, 0xdd,
	0x43, 0xb7, 0x5e, 0xf8, 0x08, 0xfc, 0x5c, 0xa6, 0xb2, 0xc8, 0x95, 0xa7, 0xc7, 0x4c, 0x57, 0xad,
	0x73, 0xc1, 0xb3, 0xd2, 0xae, 0xb3, 0xaa, 0x93, 0x27, 0xf0, 0x5f, 0xd4, 0x6b, 0xc1, 0x07, 0xf0,
	0xf5, 0xc5, 0xe1, 0xd0, 0xe6, 0x69, 0xbe, 0x97, 0xf1, 0xd9, 0xd1, 0xd4, 0xdc, 0xf7, 0xbf, 0x85,
	0xaf, 0xe6, 0xb7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x38, 0xde, 0xf0, 0x70, 0x77, 0x02, 0x00,
	0x00,
}
