// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mocker.proto

/*
Package mocker is a generated protocol buffer package.

It is generated from these files:
	mocker.proto

It has these top-level messages:
	AddHandlerRequest
	AddHandlerResponse
	RequestMatcher
	HeaderValue
	MatcherResponse
*/
package mocker

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddHandlerRequest struct {
	RequestMatcher *RequestMatcher  `protobuf:"bytes,1,opt,name=requestMatcher" json:"requestMatcher,omitempty"`
	Response       *MatcherResponse `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
}

func (m *AddHandlerRequest) Reset()                    { *m = AddHandlerRequest{} }
func (m *AddHandlerRequest) String() string            { return proto.CompactTextString(m) }
func (*AddHandlerRequest) ProtoMessage()               {}
func (*AddHandlerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddHandlerRequest) GetRequestMatcher() *RequestMatcher {
	if m != nil {
		return m.RequestMatcher
	}
	return nil
}

func (m *AddHandlerRequest) GetResponse() *MatcherResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

type AddHandlerResponse struct {
}

func (m *AddHandlerResponse) Reset()                    { *m = AddHandlerResponse{} }
func (m *AddHandlerResponse) String() string            { return proto.CompactTextString(m) }
func (*AddHandlerResponse) ProtoMessage()               {}
func (*AddHandlerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RequestMatcher struct {
	Method  string                  `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Path    string                  `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Body    string                  `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	Query   map[string]string       `protobuf:"bytes,4,rep,name=query" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Headers map[string]*HeaderValue `protobuf:"bytes,5,rep,name=headers" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *RequestMatcher) Reset()                    { *m = RequestMatcher{} }
func (m *RequestMatcher) String() string            { return proto.CompactTextString(m) }
func (*RequestMatcher) ProtoMessage()               {}
func (*RequestMatcher) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RequestMatcher) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *RequestMatcher) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RequestMatcher) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *RequestMatcher) GetQuery() map[string]string {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *RequestMatcher) GetHeaders() map[string]*HeaderValue {
	if m != nil {
		return m.Headers
	}
	return nil
}

type HeaderValue struct {
	Value []string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *HeaderValue) Reset()                    { *m = HeaderValue{} }
func (m *HeaderValue) String() string            { return proto.CompactTextString(m) }
func (*HeaderValue) ProtoMessage()               {}
func (*HeaderValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HeaderValue) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type MatcherResponse struct {
	Status int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Body   string `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *MatcherResponse) Reset()                    { *m = MatcherResponse{} }
func (m *MatcherResponse) String() string            { return proto.CompactTextString(m) }
func (*MatcherResponse) ProtoMessage()               {}
func (*MatcherResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MatcherResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MatcherResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*AddHandlerRequest)(nil), "mocker.AddHandlerRequest")
	proto.RegisterType((*AddHandlerResponse)(nil), "mocker.AddHandlerResponse")
	proto.RegisterType((*RequestMatcher)(nil), "mocker.RequestMatcher")
	proto.RegisterType((*HeaderValue)(nil), "mocker.HeaderValue")
	proto.RegisterType((*MatcherResponse)(nil), "mocker.MatcherResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Mocker service

type MockerClient interface {
	AddHandler(ctx context.Context, in *AddHandlerRequest, opts ...grpc.CallOption) (*AddHandlerResponse, error)
}

type mockerClient struct {
	cc *grpc.ClientConn
}

func NewMockerClient(cc *grpc.ClientConn) MockerClient {
	return &mockerClient{cc}
}

func (c *mockerClient) AddHandler(ctx context.Context, in *AddHandlerRequest, opts ...grpc.CallOption) (*AddHandlerResponse, error) {
	out := new(AddHandlerResponse)
	err := grpc.Invoke(ctx, "/mocker.Mocker/AddHandler", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Mocker service

type MockerServer interface {
	AddHandler(context.Context, *AddHandlerRequest) (*AddHandlerResponse, error)
}

func RegisterMockerServer(s *grpc.Server, srv MockerServer) {
	s.RegisterService(&_Mocker_serviceDesc, srv)
}

func _Mocker_AddHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockerServer).AddHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mocker.Mocker/AddHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockerServer).AddHandler(ctx, req.(*AddHandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mocker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mocker.Mocker",
	HandlerType: (*MockerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddHandler",
			Handler:    _Mocker_AddHandler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mocker.proto",
}

func init() { proto.RegisterFile("mocker.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4d, 0x4f, 0xf2, 0x40,
	0x10, 0xc7, 0x9f, 0xb6, 0xb4, 0x8f, 0x4c, 0x09, 0xea, 0x4a, 0xb0, 0xf6, 0x84, 0xe5, 0x82, 0x17,
	0x0e, 0xe5, 0x20, 0x31, 0xc1, 0xc4, 0x03, 0x09, 0x17, 0x42, 0xdc, 0x83, 0xf7, 0x42, 0x27, 0x69,
	0xc2, 0x4b, 0x61, 0xbb, 0x35, 0xe9, 0x37, 0xf0, 0xfb, 0xf9, 0x85, 0xcc, 0xbe, 0x94, 0x16, 0xc4,
	0xdb, 0xcc, 0xce, 0xfc, 0x66, 0xfe, 0x33, 0x3b, 0xd0, 0xda, 0xa6, 0xab, 0x35, 0xb2, 0xe1, 0x9e,
	0xa5, 0x3c, 0x25, 0x8e, 0xf2, 0x82, 0x2f, 0x03, 0x6e, 0xdf, 0xe2, 0x78, 0x16, 0xed, 0xe2, 0x0d,
	0x32, 0x8a, 0x87, 0x1c, 0x33, 0x4e, 0x5e, 0xa1, 0xcd, 0x94, 0x39, 0x8f, 0xf8, 0x2a, 0x41, 0xe6,
	0x19, 0x3d, 0x63, 0xe0, 0x86, 0xdd, 0xa1, 0x2e, 0x42, 0x4f, 0xa2, 0xf4, 0x2c, 0x9b, 0x8c, 0xe0,
	0x8a, 0x61, 0xb6, 0x4f, 0x77, 0x19, 0x7a, 0xa6, 0x24, 0xef, 0x4b, 0xb2, 0x44, 0x74, 0x98, 0x1e,
	0x13, 0x83, 0x0e, 0x90, 0xba, 0x12, 0xfd, 0xfa, 0x6d, 0x42, 0xfb, 0xb4, 0x1b, 0xe9, 0x82, 0xb3,
	0x45, 0x9e, 0xa4, 0xb1, 0x54, 0xd5, 0xa4, 0xda, 0x23, 0x04, 0x1a, 0xfb, 0x88, 0x27, 0xb2, 0x63,
	0x93, 0x4a, 0x5b, 0xbc, 0x2d, 0xd3, 0xb8, 0xf0, 0x2c, 0xf5, 0x26, 0x6c, 0xf2, 0x0c, 0xf6, 0x21,
	0x47, 0x56, 0x78, 0x8d, 0x9e, 0x35, 0x70, 0xc3, 0xc7, 0xcb, 0x43, 0x0d, 0xdf, 0x45, 0xce, 0x74,
	0xc7, 0x59, 0x41, 0x55, 0x3e, 0x99, 0xc0, 0xff, 0x04, 0xa3, 0x18, 0x59, 0xe6, 0xd9, 0x12, 0xed,
	0xff, 0x81, 0xce, 0x54, 0x96, 0x82, 0x4b, 0xc6, 0x1f, 0x03, 0x54, 0x35, 0xc9, 0x0d, 0x58, 0x6b,
	0x2c, 0xf4, 0x08, 0xc2, 0x24, 0x1d, 0xb0, 0x3f, 0xa3, 0x4d, 0x8e, 0x7a, 0x00, 0xe5, 0xbc, 0x98,
	0x63, 0xc3, 0x5f, 0x40, 0xab, 0x5e, 0xf2, 0x02, 0xfb, 0x54, 0x67, 0xdd, 0xf0, 0xae, 0x14, 0xa6,
	0xb0, 0x0f, 0x11, 0xaa, 0x15, 0x0c, 0xfa, 0xe0, 0xd6, 0x22, 0x55, 0x67, 0xa3, 0x67, 0x1d, 0x3b,
	0x07, 0x13, 0xb8, 0x3e, 0xfb, 0x2d, 0xb1, 0xfa, 0x8c, 0x47, 0x3c, 0xcf, 0x64, 0x6f, 0x9b, 0x6a,
	0xef, 0xb8, 0x66, 0xb3, 0x5a, 0x73, 0xb8, 0x00, 0x67, 0x2e, 0x45, 0x90, 0x29, 0x40, 0xf5, 0xb3,
	0xe4, 0xa1, 0xd4, 0xf6, 0xeb, 0xee, 0x7c, 0xff, 0x52, 0x48, 0x1f, 0xc2, 0xbf, 0xa5, 0x23, 0x4f,
	0x77, 0xf4, 0x13, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x8e, 0x2e, 0x4c, 0xca, 0x02, 0x00, 0x00,
}
