version: '3'

services:
  integration-test:
    container_name: test_integration-test
    depends_on:
      - "api"
    env_file: ./test.env
    build:
      dockerfile: ./integration-tests/Dockerfile
      context: ../

  # Services
  api:
    container_name: test_api
    image: bosonic-code/demo-mock-api
    env_file: ./test.env
    depends_on:
      - "twitch-mock"
  

  # Twitch API mock
  twitch-mock:
    container_name: test_twitch-mock
    image: bosonic/mock-api
    env_file: ./mock-api.env
